### ISSUE TITLE
choosing route, choosing new country - refresh not working

### ISSUE THREAD

**Issue by rogertosb** [greenferries/greenferries#18]
[See this gif](https://gfycat.com/weepybeautifulgadwall)

Reproduced issue several times with different countries.
Does not seem to be working properly. 
Tested with Firefox 73.0 (64-bit) - Mozilla Firefox for Ubuntu Canonical 1.0.

![refresh_not_working](https://user-images.githubusercontent.com/57436463/74915632-dd512700-53c4-11ea-8504-23e8f8169fe4.gif)

**Comment by adipasquale** [comment]
argh that's a bad one 🤦‍♂  thanks for the detailed issue I'll fix it quickly 🙇‍♀

**Comment by adipasquale** [comment]
ok this should be fixed! the route was well set to null but instantly reverted to the previous value because I had forgotten to remove the route from the query param in the url.

There is an other issue about preserving the selected country better #12 but it's not really a bug as this one was.

thanks for reporting 👍

**Comment by rogertosb** [comment]
> argh that's a bad one man_facepalming thanks for the detailed issue I'll fix it quickly bowing_woman

No worries. Very excited about your website concept. Let me know if you ever want to discuss ideas for expanding the concept! Good luck and keep working hard :)
